export { WeightStallQuiz } from './WeightStallQuiz'
export { WeightStallResult } from './WeightStallResult'
export { calculate } from './weight-stall-quiz.utils'
export type { WeightStallResult as WeightStallResultType } from './weight-stall-quiz.types'
export type { AnswerOption } from './weight-stall-quiz.types'
