export { SweetCravingQuiz } from './SweetCravingQuiz'
export { SweetCravingResult } from './SweetCravingResult'
export { calculate } from './sweet-craving.utils'
export { CAUSE_CONFIGS, QUESTIONS } from './sweet-craving.data'
export type { SweetQuizResult, SweetCategory, AnswerOption, Question } from './sweet-craving.types'
